# Generated by Django 3.1.3 on 2020-11-21 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201121_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='drone_class',
            field=models.CharField(choices=[('eco', 'Эконом'), ('bus', 'Бизнес'), ('pre', 'Премиум')], default='eco', max_length=3, verbose_name='Класс дрона'),
        ),
        migrations.AddField(
            model_name='drone',
            name='drone_image',
            field=models.ImageField(default='el.jpg', upload_to='static/image', verbose_name='Фото дрона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='drone_status',
            field=models.CharField(choices=[('fre', 'Свободен'), ('bsy', 'Занят'), ('wri', 'Списан')], default='fre', max_length=3, verbose_name='Статус дрона'),
        ),
        migrations.AddField(
            model_name='drone',
            name='production_year',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='Стоимость заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='drone_class',
            field=models.CharField(choices=[('eco', 'Эконом'), ('bus', 'Бизнес'), ('pre', 'Премиум')], default='eco', max_length=3, verbose_name='Класс дрона'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('can', 'Отменен'), ('cls', 'Закрыт'), ('per', 'Исполняется'), ('act', 'Активен')], default='act', max_length=3, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа'),
            preserve_default=False,
        ),
    ]
