# Generated by Django 3.1.3 on 2020-11-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_brand', models.CharField(max_length=150)),
                ('drone_model', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Аккаунт пользователя',
                'verbose_name_plural': 'Аккаунты пользователей',
                'ordering': ['phone_number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_point', models.CharField(max_length=255)),
                ('arrival_place', models.CharField(max_length=255)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.drone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
