# Generated by Django 3.1.3 on 2020-11-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20201128_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='login.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
